development:
  adapter: mysql2
  host: localhost
  encoding: utf8
  pool: 10
  username: root
  password:
  database: lobsters_development
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  host: localhost
  encoding: utf8
  pool: 10
  username: root
  password:
  database: lobsters_test

