development:
  smtp:
    address: mail.example.com
    port: 554
    user_name: mail
    password: password

test:
  smtp:
    address: mail.example.com
    port: 554
    user_name: mail
    password: password
